ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN npm install -g npm@9.6.5
RUN npm i -g lerna@5.4.3

RUN yarn lerna bootstrap
RUN yarn build --scope=client
RUN yarn build --scope=server

EXPOSE $SERVER_PORT
CMD cd /app/packages/server && yarn start
