export { LeaderBoardPage } from './LeaderBoardPage'
export { NotFoundPage } from './NotFoundPage'
export { ProfilePage } from './ProfilePage'
export { RootPage } from './RootPage'
export { SignInPage } from './SignInPage'
export { SignUpPage } from './SignUpPage'
export { GamePage } from './GamePage'
export { EndGameScreen } from './end game screen/EndGameScreen'
export { HomePage } from './HomePage'
